# Generated by Django 4.2.7 on 2023-12-01 12:52

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='end_date',
            field=models.DateTimeField(verbose_name=django.db.models.fields.DateTimeField),
        ),
        migrations.AlterField(
            model_name='tours',
            name='start_date',
            field=models.DateTimeField(verbose_name=django.db.models.fields.DateTimeField),
        ),
    ]
