# Generated by Django 4.2.7 on 2023-12-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_alter_comment_content_alter_news_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='name_tour',
            field=models.CharField(max_length=10),
        ),
    ]
