# Generated by Django 4.2.7 on 2023-12-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_alter_tours_name_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
