# Generated by Django 4.2.7 on 2023-12-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_booking_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='revenue',
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
