# Generated by Django 4.2.7 on 2023-12-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_remove_booking_revenue_alter_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
