# Generated by Django 4.2.7 on 2024-01-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_roles_users_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_roles',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='users_roles',
            name='users',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Users_Roles',
        ),
    ]
