# Generated by Django 4.2.7 on 2023-12-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_tours_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='duration',
        ),
    ]
