# Generated by Django 4.2.7 on 2024-01-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_remove_rating_content_alter_rating_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='news',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='tours',
            name='staff',
        ),
    ]
