# Generated by Django 4.2.7 on 2024-02-02 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_commentnews_commenttour_remove_rating_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentnews',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='commenttour',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
