# Generated by Django 4.2.7 on 2023-12-03 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_alter_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='newid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travels.news'),
        ),
    ]
