# Generated by Django 4.2.7 on 2023-12-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0012_alter_review_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='location',
        ),
    ]
