# Generated by Django 4.2.7 on 2024-02-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0013_comment_remove_commenttour_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.comment'),
        ),
    ]
