# Generated by Django 4.2.7 on 2024-02-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0014_comment_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
